### ISSUE TITLE
Pass arguments to the tests

### ISSUE THREAD

**Issue by thofma** [oscar-system/OscarDevTools.jl#1]
julia >= 1.3 can pass arguments to the test process by specifying the `test_args::Union{Cmd, Vector{String}}` keyword arguments for `Pkg.test`.

It would be great if the configuration toml would have a way to specify the arguments for the tests of an individual package. E.g.

```toml
[testoptions]
Hecke = ["short"]
```

The reason is that the Hecke tests are way too long to be useful for the upstream package testing. So I would like to limit them.

I can have a stab at it if we agree that this is a useful feature.

**Comment by benlorenz** [comment]
I like this and will implement that with a slightly different configuration syntax:, e.g.:
```toml
[pkgs]
  [pkgs.Oscar]
  branches = [ "master", "release" ]
  test = true
  
  [pkgs.Hecke]
  branches = [ "master", "release" ]
  test = true
  testoptions = [ "short" ]
```

This also allows specifying which packages should be tested, which is currently hardcoded to just Oscar.
